BuildingsSeller/WebTester/Models/ManageUserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BuildSeller.Models
{

    public class ManageUserViewModel
    {

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

BuildingsSeller/WebTester/Controllers/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using BuildSeller.Core;
using BuildSeller.Core.Model;
using BuildSeller.Core.Service;
using BuildSeller.Helpers;
using Castle.Core.Internal;
using PagedList;

namespace BuildSeller.Controllers
{

    public class UserManagerController : BaseController
    {

        private readonly IUserService userService;

        public UserManagerController(IUserService us1)
        {
            this.userService = us1;
        }

        [CustomAuthorize(Roles = UsersRoles.Administrator)]
        public ActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [CustomAuthorize(Roles = UsersRoles.Administrator)]
        public ActionResult Create(Users user)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            IList<Users> us = this.userService.Where(x => x.Login == user.Login || x.Email == user.Email);
            if (us == null)
            {
                return this.View();
            }

            this.userService.Create(user);

            return this.RedirectToAction("ManageUsers");
        }

        public ActionResult Delete(int id)
        {
            this.userService.Delete(id);

            return this.RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AddComment(int id, string comment)
        {
            Users user = this.userService.Get(id);
            user.Comments = user.Comments + Environment.NewLine + this.User.Identity.Name + " : " + comment;
            this.userService.Update(user);

            return this.Redirect(this.Request.UrlReferrer.ToString());
        }

        public ActionResult Like(int id)
        {
            Users user = this.userService.Get(id);

            Users userThatLikes = this.userService.Get(this.User.Identity.Name);

            if (!userThatLikes.UsersLiked.Where(x => x.Name == user.Login && x.IsLiked).Any())
            {
                user.Likes = ++user.Likes;
                var inter = new UserInteraction
                {
                    Name = user.Login,
                    IsLiked = true,
                    IsInteracted = true
                };
                if (userThatLikes.UsersLiked.Where(x => x.Name == user.Login && x.IsInteracted).Any())
                {
                    user.Dislikes = --user.Dislikes;
                    inter = userThatLikes.UsersLiked.Where(x => x.Name == user.Login && x.IsInteracted).FirstOrDefault();
                    inter.IsLiked = true;
                }
                else
                {
                    userThatLikes.UsersLiked.Add(inter);
                }

                this.userService.Update(user);
                this.userService.Update(userThatLikes);
            }

            return this.Redirect(this.Request.UrlReferrer.ToString());
        }

        public ActionResult DisLike(int id)
        {
            Users user = this.userService.Get(id);

            Users userThatLikes = this.userService.Get(this.User.Identity.Name);

            if (!userThatLikes.UsersLiked.Where(x => x.Name == user.Login && !x.IsLiked).Any())
            {
                user.Dislikes = ++user.Dislikes;
                var inter = new UserInteraction
                {
                    Name = user.Login,
                    IsLiked = false,
                    IsInteracted = true
                };
                if (userThatLikes.UsersLiked.Where(x => x.Name == user.Login && x.IsInteracted).Any())
                {
                    user.Likes = --user.Likes;
                    inter = userThatLikes.UsersLiked.Where(x => x.Name == user.Login && x.IsInteracted).FirstOrDefault();
                    inter.IsLiked = false;
                }
                else
                {
                    userThatLikes.UsersLiked.Add(inter);
                }

                this.userService.Update(user);
                this.userService.Update(userThatLikes);
            }

            return this.Redirect(this.Request.UrlReferrer.ToString());
        }

        [CustomAuthorize(Roles = UsersRoles.Administrator)]
        public ActionResult Ban(int id)
        {
            Users us = this.userService.Get(id);
            if (us.Login != this.User.Identity.Name)
            {
                us.Banned = !us.Banned;
                this.userService.Update(us);
                string banned = us.Banned ? "banned" : "unbanned";
                this.TempData["Message"] = ColorfullMessages.SetDivs("User " + us.Login + " has succesfully " + banned,
                MessageType.info);
            }
            else
            {
                this.TempData["Message"] = ColorfullMessages.SetDivs("You cannt ban yourself", MessageType.warning);
            }

            return this.RedirectToAction("Index");
        }

        [CustomAuthorize(Roles = UsersRoles.Administrator)]
        public ActionResult DeleteRoleForUser(string usersName, string roleName)
        {
            if (!((roleName == UsersRoles.Administrator) && this.User.Identity.Name == usersName))
            {
                bool res = this.RoleDeleteFromUser(usersName, roleName);
                if (res)
                {
                    this.ViewBag.Title = "Role deletion sucseed";

                    this.ViewBag.Message =
                    ColorfullMessages.SetDivs("Role deletion for " + usersName + " from " + roleName + " sucseed",
                    MessageType.info);
                }
                else
                {
                    this.ViewBag.Message =
                    ColorfullMessages.SetDivs("Role deletion for " + usersName + " from " + roleName + " failed",
                    MessageType.danger);
                }
            }

            string[] thisUserRoles = RolesManager.GetRolesForUser(this.userService.Get(usersName));
            string[] rolesList = RolesManager.GetAllRoles();
            this.ViewBag.Roles = new SelectList(rolesList.Except(thisUserRoles));
            this.ViewBag.UsersNames = this.GetUserOrdered(usersName);

            this.ViewBag.RolesForThisUser = thisUserRoles;

            return this.View("ManageUsers");
        }

        [CustomAuthorize(Roles = UsersRoles.Administrator)]
        public ActionResult DeleteRoleForUser1()
        {
            var list = new SelectList(RolesManager.GetAllRoles());
            this.ViewBag.Roles = list;

            this.ViewBag.UsersNames = this.GetUserNames();
            return this.View("DeleteRoleForUser");
        }

        [CustomAuthorize(Roles = UsersRoles.Administrator)]
        public ActionResult Edit(int id)
        {
            Users user = this.userService.Get(id);
            user.LoginHash = user.Login;
            return this.View(user);
        }

        public ActionResult Details(int id)
        {
            Users user = this.userService.Get(id);
            return this.View(user);
        }

        [HttpPost]
        [CustomAuthorize(Roles = UsersRoles.Administrator)]
        public ActionResult Edit(Users user)
        {
            user.Roles = this.userService.Get(user.Id).Roles;
            try
            {
                this.userService.Update(user.Id, user);
                return this.RedirectToAction("Index");
            }
            catch
            {
                return this.View();
            }
        }

        [CustomAuthorize(Roles = UsersRoles.Administrator)]
        public ActionResult GetRoles(string userName)
        {
            SelectList userNames = this.GetUserOrdered(userName);
            if (!string.IsNullOrWhiteSpace(userName))
            {
                this.ViewBag.RolesForThisUser = RolesManager.GetRolesForUser(this.userService.Get(userName));
                SelectListItem selected = userNames.First(x => x.Text == userName);
                selected.Selected = true;

                this.ViewBag.Message = ColorfullMessages.SetDivs("Roles for " + userName, MessageType.info);
            }
            else
            {
                this.ViewBag.Message = ColorfullMessages.SetDivs("No such user ", MessageType.danger);
            }

            var list = new SelectList(RolesManager.GetAllRoles());
            this.ViewBag.Roles = list;
            this.ViewBag.UsersNames = userNames;
            return this.View("ManageUsers");
        }

        public SelectList GetUserNames()
        {
            IEnumerable<Users> users = this.userService.GetAll();
            IList<string> x = new List<string>();

            foreach (Users user in users)
            {
                x.Add(user.Login);
            }

            var names = new SelectList(x);
            return names;
        }

        public SelectList GetUserOrdered(string name)
        {
            IEnumerable<Users> users = this.userService.GetAll();
            IList<string> x = new List<string>();
            x.Add(name);
            foreach (Users user in users)
            {
                if (user.Login != name)
                {
                    x.Add(user.Login);
                }
            }

            var names = new SelectList(x);
            return names;
        }

        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            this.ViewBag.CurrentSort = sortOrder;
            this.ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "name_desc" : string.Empty;
            this.ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            this.ViewBag.Message = this.TempData["Message"];
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            this.ViewBag.CurrentFilter = searchString;

BuildingsSeller/WebTester/Views/UserManager/Create.cshtml
@model BuildSeller.Core.Model.Users

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Users</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Login, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login)
                @Html.ValidationMessageFor(model => model.Login)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Patronymic, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Patronymic)
                @Html.ValidationMessageFor(model => model.Patronymic)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activated, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Activated)
                @Html.ValidationMessageFor(model => model.Activated)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BuildingsSeller/WebTester/Views/UserManager/DeleteRoleForUser.cshtml
@using System.Diagnostics

@{
    ViewBag.Title = "DeleteRoleForUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3>Delete A User from a Role</h3>

<h2>@Html.Raw(@ViewBag.Message)</h2>
@using (Html.BeginForm("DeleteRoleForUser", "UserManager"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <p>
        Username : @try
                   {
                       @Html.DropDownList("UsersName", ViewBag.UsersNames as SelectList, new { @id = "userNamesList" })
                   }
                   catch (Exception ex)
                   {
                       Debug.WriteLine(ex.ToString());
                   }

        Role Name: @try
                   {
                       @Html.DropDownList("RoleName", ViewBag.Roles as SelectList)
                   }
                   catch (Exception ex)
                   {
                       Debug.WriteLine(ex.ToString());
                   }
    </p>

    <input type="submit" value="Delete this user from Role" />
}

BuildingsSeller/WebTester/Views/UserManager/Details.cshtml
@model BuildSeller.Core.Model.Users

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Users</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Activated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaidUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaidUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Banned)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Banned)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaidSeller)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaidSeller)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Login)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Login)
        </dd>

      
        <dt>
            @Html.DisplayNameFor(model => model.Patronymic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patronymic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Likes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Likes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Dislikes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dislikes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisterDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisterDateTime)
        </dd>
        <dd>
            Отзывы
        </dd>
        <dd>
            <span style="white-space: pre-line">@Model.Comments</span>
        </dd>
        <dd>
            
            <div class="btn-group">
                <button type="button" class="btn btn-default" onclick=" location.href = '@Url.Action("Like", "UserManager", new { id = Model.Id })    ' ">Like</button>
                <button type="button" class="btn btn-default" onclick=" location.href = '@Url.Action("DisLike", "UserManager", new { id = Model.Id })    ' ">Dislike</button>

            </div>
        </dd>
    </dl>
</div>
@using (Html.BeginForm("AddComment", "UserManager", FormMethod.Post))
{
    @Html.HiddenFor(model => model.Id)
    <p>
        Add comment: @Html.TextBox("Comment", string.Empty)
        <input type="submit" value="Add" />
    </p>
}
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BuildingsSeller/WebTester/Views/UserManager/Edit.cshtml
@model BuildSeller.Core.Model.Users

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Users</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        @Html.HiddenFor(model => model.LoginHash)
        <div class="form-group">
            @Html.LabelFor(model => model.Login, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login)
                @Html.ValidationMessageFor(model => model.Login)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Patronymic, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Patronymic)
                @Html.ValidationMessageFor(model => model.Patronymic)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activated, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Activated)
                @Html.ValidationMessageFor(model => model.Activated)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Banned, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Banned)
                @Html.ValidationMessageFor(model => model.Banned)
            </div>
        </div>
      
        <div class="form-group">
            @Html.LabelFor(model => model.RegisterDateTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegisterDateTime)
                @Html.ValidationMessageFor(model => model.RegisterDateTime)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BuildingsSeller/WebTester/Views/UserManager/Index.cshtml
@using PagedList.Mvc
@using BuildSeller.Core.Model
@model PagedList.IPagedList<BuildSeller.Core.Model.Users>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<h2>@Html.Raw(@ViewBag.Message)</h2>
<p>
    @Html.ActionLink("Create New", "Create") | 
    
    @Html.ActionLink("Manage roles", "ManageUsers")
</p>

@using (Html.BeginForm("Index", "UserManager", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table table-hover">
    <tr>
        <th>Login
        </th>
        <th>FirstName
        </th>
        <th>
            @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>Patronymic
        </th>
        <th>Email
        </th>
        <th>Activated
        </th>
        <td>IsBanned
        </td>
        <th>
            @Html.ActionLink("Created", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

    @foreach (Users item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Login)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Patronymic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Banned)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegisterDateTime)
            </td>
            <td>
                <div class="btn-group">
                    <a class="btn btn-primary" href="#"><i class="icon-user icon-white"></i>Пользователь</a>
                    <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Edit", "Edit", new { id = item.Id })</li>

                        <li>@Html.ActionLink("Details", "Details", new { id = item.Id })</li>

                        <li>
                            @Html.ActionLink("Ban/Unban", "Ban", new { id = item.Id })</li>

                        <li class="divider"></li>
                        <li>@Html.ActionLink("Delete", "Delete", new { id = item.Id })</li>

                    </ul>
                </div>
            </td>
        </tr>
    }
</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", 
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

BuildingsSeller/WebTester/Views/UserManager/ManageUsers.cshtml
@using System.Diagnostics
@{
    ViewBag.Title = "ManageUsers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $('#EnterprisePull').hide();

        $(function() {
            $('#thickboxButton').click(function() {
                $('#thickboxId').click();
            });
        });
        $(function() {
            $('#userNamesList').change(function() {
                // alert("asd");
                $("input[id=EnterprisePull]").click();
                //    $('form#myForm').submit();
            });
        });
        //  $(".userForm").hover(function () {
        //   $("#usName").val($("#userNamesList option:selected").text());
        // });
    });
</script>

<div class="spacerBody">
    <p>&nbsp;</p>
    <h2>@Html.Raw(@ViewBag.Message)</h2>
    <p>
        @Html.ActionLink("Show users list", "Index")|
        @Html.ActionLink("Create New user", "Create")
    </p>
    <h2>Role Add to User</h2>

    @using (Html.BeginForm("RoleAddToUser", "UserManager", null, FormMethod.Post, new { @class = "userForm" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="message-success">@ViewBag.ResultMessage</div>
        <p>
            Username :
            @try
            {
                @Html.DropDownList("UsersName", ViewBag.UsersNames as SelectList, new { @id = "userNamesList" })
            }
            catch (Exception)
            {
                throw;
            }
            Role Name:
            @try
            {
                @Html.DropDownList("RoleName", ViewBag.Roles as SelectList, new { @class = "rolesList" })
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.ToString());
            }
        </p>
        <input type="submit" id="EnterprisePush" name="btnSubmit" value="AddUserToSelectedRole" />
        <input type="submit" id="EnterprisePull" name="btnSubmit" value="Get" />
    }

    <div class="hr"></div>

    @if (ViewBag.RolesForThisUser != null)
    {
        <text>
            <h3>Roles for this user </h3>

            <table class="table">
                <tr>
                    <th>Role description
                    </th>
                    <th>Delete user from this role
                    </th>
                </tr>
                <tr>

                    @foreach (string s in ViewBag.RolesForThisUser)
                    {
                        <tr>
                            <td>
                                <li>@s </li>
                            </td>
                            <td>
                                @Html.ActionLink("Delete", "DeleteRoleForUser", new { usersName = (ViewBag.UsersNames as SelectList).First().Text, roleName = s })
                            </td>
                        </tr>
                    }
                </tr>
            </table>
        </text>
    }
</div>