BuildingsSeller/WebTester/Controllers/StatisticsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BuildSeller.Core.Model;
using BuildSeller.Helpers;
using BuildSeller.Models;
using BuildSeller.Service;

namespace BuildSeller.Controllers
{

    public class StatisticsController : BaseController
    {

        private readonly IBuildCategoriesService categoriesService;

        private readonly IRealtyService realtyService;

        public StatisticsController(IBuildCategoriesService bsService, IRealtyService service)
        {
            this.realtyService = service;
            this.categoriesService = bsService;
        }

        public ActionResult Index()
        {
            this.ViewBag.Message = this.TempData["Message"];
            IEnumerable<BuildCategories> cats = this.categoriesService.GetAll();
            var CatsName = new string[cats.Count()];
            int i = 0;
            foreach (BuildCategories cat in cats)
            {
                CatsName[i] = cat.CatName;
                i++;
            }

            this.ViewBag.Cats = new SelectList(CatsName);
            var model = new StatModel();
            model.Until = this.realtyService.GetAll().OrderBy(x => x.Created).FirstOrDefault().Created;
            model.ToTime = this.realtyService.GetAll().OrderByDescending(x => x.Created).FirstOrDefault().Created;
            return View(model);
        }

        public ActionResult GetStatistic(StatModel model, string cats)
        {
            int stat =
            this.realtyService.GetAllIncluding(x => x.BuildCategory)
            .Count(
            x =>
            x.Created >= model.Until && x.Created <= model.ToTime && x.IsSold &&
            x.BuildCategory.CatName == cats);
            this.TempData["Message"] =
            ColorfullMessages.SetDivs(
            "Sold count for " + cats + " of period " + model.Until + " to " + model.ToTime + " : " + stat,
            MessageType.info);
            return this.RedirectToAction("Index");
        }
    }
}

BuildingsSeller/WebTester/Views/Statistics/Index.cshtml
@model BuildSeller.Models.StatModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>@Html.Raw(@ViewBag.Message)</h3>
<link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
        <script src="../../Scripts/jquery-1.10.2.js" type="text/javascript"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">

@using (Html.BeginForm("GetStatistic", "Statistics", FormMethod.Get))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.Label("Choose cat", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cats", ViewBag.Cats as SelectList, new { @id = "catsList", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Until, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Until)
                @Html.ValidationMessageFor(model => model.Until)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToTime)
                @Html.ValidationMessageFor(model => model.ToTime)
                
 
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="GetStat" class="btn btn-default" />
            </div>
        </div>
    </div>
}