BuildingsSeller/WebTester/Controllers/GlobalMessengerController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BuildSeller.Core.Model;
using BuildSeller.Service;

namespace BuildSeller.Controllers
{

    public class GlobalMessengerController : Controller
    {

        private readonly IBuildCategoriesService buildCategoriesService;

        private readonly ISubscribeService subscribeService;

        public GlobalMessengerController(IBuildCategoriesService categoriesService, ISubscribeService subscribService)
        {
            this.buildCategoriesService = categoriesService;
            this.subscribeService = subscribService;
        }

        public ActionResult Index()
        {
            this.ViewBag.Message = this.TempData["Message"];
            return this.View(this.buildCategoriesService.GetAll());
        }

        public ActionResult Details(int id)
        {
            return this.View(this.GetSubscribersForCat(id));
        }

        public ActionResult CreateMessage(int id)
        {
            return View(id);
        }

        public List<Users> GetSubscribersForCat(int id)
        {
            string catName = this.buildCategoriesService.Get(id).CatName;
            IQueryable<Subscribe> subscriptions =
            this.subscribeService.GetAllIncluding(x => x.Subscriber).Where(x => x.Name == catName);
            var users = new List<Users>();
            foreach (Subscribe subscr in subscriptions)
            {
                users.Add(subscr.Subscriber);
            }

            return users;
        }

        [HttpPost]
        public ActionResult SendMessage(int id, string message, string title)
        {
            GlobalMessenger.Send(message, title, string.Empty, this.GetSubscribersForCat(id));
            this.TempData["Message"] = "<div class='alert alert-success'>" + "Message sended succesfully" + "</div>";
            return this.RedirectToAction("Index");
        }
    }
}

BuildingsSeller/WebTester/Controllers/PaymentsController.cs
using System.Web.Mvc;
using BuildSeller.Core;
using BuildSeller.Core.Model;
using BuildSeller.Core.Service;
using BuildSeller.Helpers;

namespace BuildSeller.Controllers
{

    public class PaymentsController : BaseController
    {

        private readonly IUserService userService;

        public PaymentsController(IUserService userServi)
        {
            this.userService = userServi;
        }

        public ActionResult Index()
        {
            this.ViewBag.Message = this.TempData["Message"];
            return this.View();
        }

        public ActionResult UserPayment()
        {
            Users user = this.userService.Get(this.User.Identity.Name);
            if (user == null)
            {
                return this.RedirectToAction("Index");
            }
            if (!user.PaidUser)
            {
                if (!RolesManager.IsUserInRole(User.Identity.Name, UsersRoles.User))
                {
                    user.AddUserToRole(UsersRoles.User);
                }

                user.PaidUser = true;
                this.userService.Update(user);
                this.TempData["Message"] = ColorfullMessages.SetDivs("Payment for being user succseed ",
                MessageType.success);
            }
            else
            {
                this.TempData["Message"] = ColorfullMessages.SetDivs("You already paid for being user ",
                MessageType.warning);
            }

            return this.RedirectToAction("Index");
        }

        public ActionResult SellerPayment()
        {
            Users user = this.userService.Get(this.User.Identity.Name);
            if (user == null)
            {
                return this.RedirectToAction("Index");
            }
            if (!user.PaidSeller)
            {
                if (!RolesManager.IsUserInRole(User.Identity.Name, UsersRoles.Seller))
                {
                    user.AddUserToRole(UsersRoles.Seller);
                }

                user.PaidSeller = true;
                this.userService.Update(user);
                this.TempData["Message"] = ColorfullMessages.SetDivs("Payment for being seller succseed ",
                MessageType.success);
            }
            else
            {
                this.TempData["Message"] = ColorfullMessages.SetDivs("You already paid for being seller ",
                MessageType.warning);
            }

            return this.RedirectToAction("Index");
        }
    }
}

BuildingsSeller/WebTester/Controllers/RealtyController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using BuildSeller.Core;
using BuildSeller.Core.Model;
using BuildSeller.Core.Service;
using BuildSeller.Helpers;
using BuildSeller.Models;
using BuildSeller.Service;
using Castle.Core.Internal;
using PagedList;

namespace BuildSeller.Controllers
{

    public class RealtyController : BaseController
    {

        private static readonly Dictionary<string, bool> isCurrentUserListRented = new Dictionary<string, bool>();
        private static readonly Dictionary<string, string> currentUserCategory = new Dictionary<string, string>();

        internal static readonly DateTime DateDefault = DateTime.MinValue;

        private readonly IBuildCategoriesService buildCategoriesService;

        private readonly IRealtyService realtyService;

        private readonly IUserService userService;

        public RealtyController(IRealtyService realtyServic, IUserService userServi,
        IBuildCategoriesService categoriesService)
        {
            this.realtyService = realtyServic;
            this.userService = userServi;
            this.buildCategoriesService = categoriesService;
        }

        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page, bool? forRent, string category)
        {
            if (!isCurrentUserListRented.ContainsKey(this.User.Identity.Name))
            {
                isCurrentUserListRented.Add(this.User.Identity.Name, true);
            }
            if (!currentUserCategory.ContainsKey(this.User.Identity.Name))
            {
                currentUserCategory.Add(this.User.Identity.Name, string.Empty);
            }

            this.ViewBag.CurrentSort = sortOrder;
            this.ViewBag.CatSortParm = string.IsNullOrEmpty(sortOrder) ? "cat_desc" : string.Empty;
            this.ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            this.ViewBag.Message = this.TempData["Message"];
            IEnumerable<BuildCategories> cats = this.buildCategoriesService.GetAll();
            var CatsName = new string[cats.Count() + 1];
            CatsName[0] = "All";

            ViewBag.CurrCat = "All";
            int i = 1;
            foreach (BuildCategories cat in cats)
            {
                CatsName[i] = cat.CatName;
                i++;
            }

            this.ViewBag.Cats = new SelectList(CatsName);
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            if (!category.IsNullOrEmpty())
            {
                ViewBag.CurrCat = category;
                currentUserCategory[this.User.Identity.Name] = category;
            }

            if (forRent != null)
            {
                isCurrentUserListRented[this.User.Identity.Name] = (bool)forRent;
            }

            this.ViewBag.CurrentFilter = searchString;
            bool rent = isCurrentUserListRented[this.User.Identity.Name];
            this.ViewBag.Rent = rent;
            IEnumerable<Realty> realties;
            if (this.TempData["Temp"] == null)
            {
                if (currentUserCategory[this.User.Identity.Name].IsEmpty() ||
                currentUserCategory[this.User.Identity.Name] == "All")
                {
                    realties = this.realtyService.GetAllIncluding(realty => realty.Owner, realty => realty.BuildCategory)
                    .Where(x => !x.IsSold && x.IsForRent == !rent);
                }
                else
                {
                    var cat = currentUserCategory[this.User.Identity.Name];
                    realties = this.realtyService.GetAllIncluding(realty => realty.Owner, realty => realty.BuildCategory)
                    .Where(x => !x.IsSold && x.IsForRent == !rent && x.BuildCategory.CatName == cat);
                }
            }
            else
            {
                realties = (IEnumerable<Realty>)this.TempData["Temp"];
            }

            if (!string.IsNullOrEmpty(searchString))
            {
                realties = realties.Where(s => s.Named.ToUpper().Contains(searchString.ToUpper())
                || s.Description.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "cat_desc":
                    realties = realties.OrderByDescending(s => s.BuildCategory.CatName);
                    break;
                case "Date":
                    realties = realties.OrderBy(s => s.Created);
                    break;
                case "date_desc":
                    realties = realties.OrderByDescending(s => s.Created);
                    break;
                default:
                    realties = realties.OrderBy(s => s.Created);
                    break;
            }

            int pageSize = 5;
            int pageNumber = page ?? 1;
            return View(realties.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Find(string sity, string category)
        {

            IEnumerable<BuildCategories> cats = this.buildCategoriesService.GetAll();
            var CatsName = new string[cats.Count()];
            int i = 0;
            foreach (BuildCategories cat in cats)
            {
                CatsName[i] = cat.CatName;
                i++;
            }

            this.ViewBag.Cats = new SelectList(CatsName);
            int pageSize = 0;
            IEnumerable<Realty> realties;
            if (sity.IsNullOrEmpty() && category.IsNullOrEmpty())
            {
                this.TempData["Message"] = ColorfullMessages.SetDivs("Nothing to seek", MessageType.info);
                return this.RedirectToAction("Index");
            }

            if (!sity.IsNullOrEmpty() && !category.IsNullOrEmpty())
            {
                realties = this.realtyService.GetAllIncluding(realty => realty.BuildCategory, realty => realty.Owner)
                .Where(x => !x.IsSold
                && x.Address.ToUpper().Contains(sity.ToUpper())
                && x.BuildCategory.CatName.ToUpper() == category.ToUpper());
                this.TempData["Message"] = ColorfullMessages.SetDivs("Seek by city and category", MessageType.info);
            }
            else
            {
                realties = this.realtyService.GetAllIncluding(realty => realty.BuildCategory, realty => realty.Owner)
                .Where(x => !x.IsSold
                && x.Address.ToUpper().Contains(sity.ToUpper()));
                this.TempData["Message"] = ColorfullMessages.SetDivs("Seek by city", MessageType.info);
            }

            if (realties == null || realties.Count() == 0)
            {
                this.TempData["Message"] = ColorfullMessages.SetDivs("Found 0 matches", MessageType.info);
                return this.RedirectToAction("Index");
            }

            realties = realties.OrderBy(x => x.Created);
            pageSize = realties.Count();
            this.ViewBag.Message = this.TempData["Message"];
            return View("Index", realties.ToPagedList(1, pageSize));
        }

        public ActionResult Details(int id)
        {
            return View(this.realtyService.
            GetAllIncluding(realty => realty.Owner,
            realty => realty.Photos,
            realty => realty.BuildCategory)
            .FirstOrDefault(real => real.Id == id));
        }

        [CustomAuthorize(Roles = UsersRoles.Seller)]
        public ActionResult Create()
        {
            IEnumerable<BuildCategories> cats = this.buildCategoriesService.GetAll();
            var CatsName = new string[cats.Count()];
            int i = 0;
            foreach (BuildCategories cat in cats)
            {
                CatsName[i] = cat.CatName;
                i++;
            }

            this.ViewBag.Cats = new SelectList(CatsName);
            return this.View();
        }

        public ActionResult SearchSameRealties(int id)
        {
            Realty realt = this.realtyService.GetAllIncluding(x => x.BuildCategory).FirstOrDefault(x => x.Id == id);
            var model = new RealtySearchModel
            {
                CreatedHigh = realt.Created.AddDays(30),
                CreatedLow = realt.Created.AddDays(-30),
                IsForRent = realt.IsForRent,
                PriceHigh = decimal.Multiply(realt.Price, 1.5m),
                PriceLow = decimal.Multiply(realt.Price, 0.75m),
                SquareHigh = realt.Square * 1.5f,
                SquareLow = realt.Square * 0.75f,
                Town = realt.Address,
                Category = realt.BuildCategory.CatName
            };
            return this.View(model);
        }

        [HttpPost]
        public ActionResult SearchSameRealties(RealtySearchModel model)
        {
            IEnumerable<Realty> realt = this.realtyService.GetAllIncluding(x => x.BuildCategory, realty => realty.Owner)
            .Where(x => x.IsForRent == model.IsForRent
            && (string.IsNullOrEmpty(model.Town) || x.Address.Contains(model.Town))
            && !x.IsSold
            && (string.IsNullOrEmpty(model.Category) || x.BuildCategory.CatName ==
            model.Category)
            && (model.PriceLow == 0 || x.Price >= model.PriceLow)
            && (model.PriceHigh == 0 || x.Price <= model.PriceHigh)
            && (model.SquareLow == 0 || x.Square >= model.SquareLow)
            && (model.SquareHigh == 0 || x.Square <= model.SquareHigh)
            && (model.CreatedLow == DateDefault || x.Created >= model.CreatedLow)
            && (model.CreatedHigh == DateDefault || x.Created <= model.CreatedHigh));
            this.TempData["Temp"] = realt;
            return this.RedirectToAction("Index");
        }

        [HttpPost]
        [CustomAuthorize(Roles = UsersRoles.Seller)]

BuildingsSeller/WebTester/Controllers/SubscribesController.cs
using System.Linq;
using System.Web.Mvc;
using BuildSeller.Core;
using BuildSeller.Core.Model;
using BuildSeller.Core.Service;
using BuildSeller.Helpers;
using BuildSeller.Service;

namespace BuildSeller.Controllers
{

    public class SubscribesController : BaseController
    {

        private readonly IBuildCategoriesService buildCategoriesService;

        private readonly ISubscribeService subscribeService;

        private readonly IUserService userService;

        public SubscribesController(ISubscribeService subscribService, IBuildCategoriesService categoriesService,
        IUserService userServic)
        {
            this.subscribeService = subscribService;
            this.buildCategoriesService = categoriesService;
            this.userService = userServic;
        }

        public ActionResult Index()
        {
            this.ViewBag.Message = this.TempData["SubscrResult"];
            return this.View(this.buildCategoriesService.GetAll());
        }

        [CustomAuthorize(Roles = UsersRoles.User)]
        public ActionResult Subscribe(int id)
        {
            BuildCategories cat = this.buildCategoriesService.Get(id);
            if (!this.subscribeService.GetAllIncluding(c => c.Subscriber).Where(x => x.Name == cat.CatName && x.Subscriber.Login == User.Identity.Name).Any())
            {
                var subscr = this.userService.Get(this.User.Identity.Name);
                if (!subscr.PaidUser)
                {
                    this.TempData["SubscrResult"] =
                    ColorfullMessages.SetDivs("You must pay to subscribe", MessageType.warning);
                }
                else
                {
                    var subscription = new Subscribe
                    {
                        Description = cat.CatName,
                        Name = cat.CatName,
                        Subscriber = subscr
                    };

                    this.subscribeService.Create(subscription);

                    this.TempData["SubscrResult"] =
                    ColorfullMessages.SetDivs("Subscription on " + cat.CatName + " were created", MessageType.success);
                }
            }
            else
            {
                this.TempData["SubscrResult"] =
                ColorfullMessages.SetDivs("Subscription on " + cat.CatName + " already exists", MessageType.warning);
            }

            return this.RedirectToAction("Index");
        }

        public ActionResult UnSubscribe(int id)
        {
            Subscribe subToDelete = this.subscribeService.Get(id);
            this.subscribeService.Delete(id);

            this.TempData["SubscrResult"] =
            ColorfullMessages.SetDivs("Subscription on" + subToDelete.Name + " were deleted", MessageType.info);
            return this.RedirectToAction("ShowSubscriptions", "Account");
        }
    }
}

BuildingsSeller/WebTester/Views/Shared/_Layout.cshtml
@using BuildSeller.Core
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @Langs.Lang.WebBuildings</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .cbp-spmenu {
            background: #47a3da;
            position: fixed;
        }

            .cbp-spmenu h3 {
                color: #afdefa;
                font-size: 1.9em;
                padding: 20px;
                margin: 0;
                font-weight: 300;
                background: #0d77b6;
            }

            .cbp-spmenu a {
                display: block;
                color: #fff;
                font-size: 1.1em;
                font-weight: 300;
            }

                .cbp-spmenu a:hover {
                    background: #258ecd;
                }

                .cbp-spmenu a:active {
                    background: #afdefa;
                    color: #47a3da;
                }

        /* Orientation-dependent styles for the content of the menu */

        .cbp-spmenu-vertical {
            width: 240px;
            height: 100%;
            top: 0;
            z-index: 1000;
        }

            .cbp-spmenu-vertical a {
                border-bottom: 1px solid #258ecd;
                padding: 1em;
            }

        .cbp-spmenu-horizontal {
            width: 100%;
            height: 150px;
            left: 0;
            z-index: 1000;
            overflow: hidden;
        }

            .cbp-spmenu-horizontal h3 {
                height: 100%;
                width: 20%;
                float: left;
            }

            .cbp-spmenu-horizontal a {
                float: left;
                width: 20%;
                padding: 0.8em;
                border-left: 1px solid #258ecd;
            }

        /* Vertical menu that slides from the left or right */

        .cbp-spmenu-left {
            top: 51px;
            left: -225px;
        }

        .cbp-spmenu-right {
            right: -240px;
        }

        .cbp-spmenu-left.cbp-spmenu-open {
            left: 0px;
        }

        .cbp-spmenu-right.cbp-spmenu-open {
            right: 0px;
        }

        /* Horizontal menu that slides from the top or bottom */

        .cbp-spmenu-top {
            top: -150px;
        }

        .cbp-spmenu-bottom {
            bottom: -150px;
        }

        .cbp-spmenu-top.cbp-spmenu-open {
            top: 0px;
        }

        .cbp-spmenu-bottom.cbp-spmenu-open {
            bottom: 0px;
        }

        /* Push classes applied to the body */

        .cbp-spmenu-push {
            overflow-x: hidden;
            position: relative;
            left: 0;
        }

        .cbp-spmenu-push-toright {
            left: 240px;
        }

        .cbp-spmenu-push-toleft {
            left: -240px;
        }

        /* Transitions */

        .cbp-spmenu,
        .cbp-spmenu-push {
            -webkit-transition: all 0.3s ease;
            -moz-transition: all 0.3s ease;
            transition: all 0.3s ease;
        }
    </style>
    <script src="../../Scripts/jquery-1.10.2.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {

        });
        jQuery(function ($) {
            var IsMouseOnMenu = false;
            var currentMousePos = { x: -1, y: -1 };
            $(document).mousemove(function (event) {
                currentMousePos.x = event.pageX;
                currentMousePos.y = event.pageY;
                if (currentMousePos.x < 50 && !IsMouseOnMenu) {
                    $('#cbp-spmenu-s1').toggleClass('cbp-spmenu-open');
                    IsMouseOnMenu = true;
                } else {
                    if (currentMousePos.x > 150 && IsMouseOnMenu) {
                        $('#cbp-spmenu-s1').toggleClass('cbp-spmenu-open');
                        IsMouseOnMenu = false;
                    }
                }
            });
        });

    </script>
    <meta name="description" content="BuildSeller site" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(Langs.Lang.HomeTitle, "Index", "Home")</li>
                    <li>@Html.ActionLink(Langs.Lang.About, "About", "Home")</li>


                    @if (RolesManager.IsUserInRole(User.Identity.Name, UsersRoles.User))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">@Langs.Lang.UserFunc <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink(Langs.Lang.Payments, "Index", "Payments")</li>

                                <li>@Html.ActionLink("Statistics", "Index", "Statistics")</li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink(Langs.Lang.Subscribe, "Index", "Subscribes")</li>
                    }
                    <li>@Html.ActionLink(Langs.Lang.Realty, "Index", "Realty")</li>

                    @if (RolesManager.IsUserInRole(User.Identity.Name, UsersRoles.Administrator))
                    {
                        <li>@Html.ActionLink(Langs.Lang.Categories, "Index", "BuildCategories")</li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin func <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("ManageUsers", "Index", "UserManager")</li>

                                <li>@Html.ActionLink("Messenger", "Index", "GlobalMessenger")</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
            <h3>Menu</h3>

            @if (RolesManager.IsUserInRole(User.Identity.Name, UsersRoles.User))
            {
                @Html.ActionLink(@Langs.Lang.MyCabinet, "Manage", "Account", null, new { title = "Manage" })

                @Html.ActionLink(Langs.Lang.Show + " my " + Langs.Lang.Subscribe, "ShowSubscriptions", "Account")
            }
            @if (RolesManager.IsUserInRole(User.Identity.Name, UsersRoles.Seller))
            {
                 
                @Html.ActionLink(Langs.Lang.Realty + " Of mine", "MyRealties", "Account")
            }
        </nav>
        @RenderBody()
        <hr />
        <footer>
            <div class="btn-group dropup">
                <button type="button" class="btn btn-default">Help</button>
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                    <span class="sr-only">Help</span>
                </button>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                </ul>
            </div>
            <p>&copy; @DateTime.Now.Year - EWebShop Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)
</body>
</html>